WIP Juanvqz/change json to yaml format
creativecommons/ccos-scripts pull request #88
Opened 2020-09-27 16:15 UTC by JuanVqz

## Fixes

Fixes #85  by @dhruvkb 

## Description
change JSON to YAML format

## Technical details

## Tests

## Screenshots

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-09-27 16:19 UTC, JuanVqz commented
@dhruvkb I didn't find the corresponding `\uD83D\uDFE5` emoji code in this [cheat sheet](https://www.webfx.com/tools/emoji-cheat-sheet/).
What should I do?

2020-09-27 16:22 UTC, dhruvkb commented
@JuanVqz please leave them as codepoints for now. We can find replacements for them later.

2020-09-27 17:44 UTC, JuanVqz commented
@dhruvkb  Would you check it, please? I think it is finished.

2020-09-28 06:26 UTC, dhruvkb requested changes
Apart from the few changes pointed below, this is great work! However you will also need to make the corresponding changes to the Python code in `get_labels.py` that reads and interprets these files as that has been written for the JSON format.

2020-09-28 06:26 UTC, dhruvkb commented on normalize_repos/labels.yml
> +    name: "priority"
Values that are plain strings do not need to be surrounded in quotes.

2020-09-28 06:26 UTC, dhruvkb commented on normalize_repos/labels.yml
> +        emoji: "\uD83D\uDEA7"
Please replace emojis that are present in the cheat sheet with the colon-representation. Only leave those that are absent as codepoints.
```suggestion
        emoji: ":construction:"
```

2020-10-07 14:43 UTC, closed without merging

2020-10-07 14:44 UTC, JuanVqz commented
I don't know why the PR repo says unknown repository that is the reason I open another PR