Add support for non-"master" default branches in normalize_repos
creativecommons/ccos-scripts pull request #95
Opened 2020-10-08 19:00 UTC by akmadian

## Fixes

Fixes #48 by @TimidRobot 

## Description

This PR updates the normalize_repos workflow to add support for repos with default branches that are not named "master".

I think I've done everything that's needed, if I missed anything please let me know and I'll follow up within a day or two : )

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-10-08 22:21 UTC, zackkrida commented
Just noting that this repo: https://github.com/creativecommons/og-image-generator is already using `main` as the default branch, in case anyone needs a branch to test against.

2020-10-09 01:36 UTC, dhruvkb requested changes
This PR includes code from your other PR #94.

2020-10-18 19:54 UTC, akmadian commented
Whoops, I guess my stashing got a bit messy :/

2020-10-19 09:54 UTC, dhruvkb approved these changes

2020-10-23 15:34 UTC, merged